name: Build Binaries

on: [push, pull_request]

jobs:
    build_debian_buster:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - name: Build
          run: cd $GITHUB_WORKSPACE && docker build --tag android-sdr-kit .

        - name: Package binaries
          run: docker run --name build android-sdr-kit /bin/bash -l -c "cd /root && ./package.sh"

        - name: Recover binaries
          working-directory: ${{runner.workspace}}
          run: docker cp build:/root/android-sdr-kit.tar.gz ./

        - name: Save Deb Archive
          uses: actions/upload-artifact@v2
          with:
              name: android-sdr-kit
              path: ${{runner.workspace}}/android-sdr-kit.tar.gz
